lib/heroes_oracle_web/router.ex
defmodule HeroesOracleWeb.Router do
  use HeroesOracleWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.Pipeline, module: HeroesOracle.Guardian,
                             error_handler: HeroesOracleWeb.HttpErrorHandler
    plug Guardian.Plug.VerifySession, claims: %{"typ" => "access"}
    plug Guardian.Plug.VerifyHeader, claims: %{"typ" => "access"}
  end

  pipeline :browser_auth do
    plug Guardian.Plug.EnsureAuthenticated
  #   plug Guardian.Plug.EnsureAuthenticated, %{"typ" => "access", handler: HeroesOracleWeb.HttpErrorHandler}
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HeroesOracleWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/heroes", HeroController do
      resources "/talents", TalentController
      resources "/aspects", AspectController
    end
    resources "/sessions", SessionController, only: [:new, :create]
    get "/sessions", SessionController, :delete
  end

  scope "/", HeroesOracleWeb do
    pipe_through [:browser, :browser_auth]

    resources "/heroes/:id/aspects", AspectController
    resources "/users", UserController, only: [:show, :update, :index]
  end

  # Other scopes may use custom stacks.
  # scope "/api", HeroesOracleWeb do
  #   pipe_through :api
  # end
end

lib/heroes_oracle/heroes/hero.ex
defmodule HeroesOracle.Heroes.Hero do
  use Ecto.Schema
  import Ecto.Changeset
  alias HeroesOracle.Heroes.{Hero, Talent, Aspect, HeroType, HeroRole}


  schema "heroes" do
    field :name, :string
    has_many :talents, Talent
    belongs_to :role, HeroRole, foreign_key: :role_id
    belongs_to :type, HeroType, foreign_key: :type_id
    has_many :aspects, Aspect

    timestamps()
  end

  def changeset(%Hero{} = hero, attrs) do
    hero
    |> cast(attrs, [:name, :role_id, :type_id])
    |> validate_required([:name, :role_id, :type_id])
  end
end

lib/heroes_oracle/heroes/hero_type.ex
defmodule HeroesOracle.Heroes.HeroType do
  use Ecto.Schema
  import Ecto.Changeset
  # alias HeroesOracle.Heroes.{Hero}


  schema "ref_heroes_types" do
    field :name, :string
  end

  # @doc false
  # def changeset(%Hero{} = hero, attrs) do
  #   hero
  #   |> cast(attrs, [:name])
  #   |> validate_required([:name])
  # end
end

lib/heroes_oracle_web/controllers/hero_controller.ex
defmodule HeroesOracleWeb.HeroController do
  use HeroesOracleWeb, :controller

  alias HeroesOracle.Heroes
  alias HeroesOracle.Heroes.{Hero, HeroType}
  alias HeroesOracle.Repo

  def index(conn, _params) do
    heroes = Heroes.list_heroes()
    render(conn, "index.html", heroes: heroes)
  end

  def get_heroes_types_opts do
    heroes_types = Heroes.list_heroes_types()
    |> Enum.map(&{&1.name, &1.id})
  end

  def get_heroes_roles_opts do
    heroes_roles = Heroes.list_heroes_roles()
    |> Enum.map(&{&1.name, &1.id})
  end

  def new(conn, _params) do
    changeset = Heroes.change_hero(%Hero{})
    render(conn, "new.html",
      changeset: changeset,
      heroes_types: get_heroes_types_opts,
      heroes_roles: get_heroes_roles_opts)
  end

  def create(conn, %{"hero" => hero_params}) do
    case Heroes.create_hero(hero_params) do
      {:ok, hero} ->
        conn
        |> put_flash(:info, "Hero created successfully.")
        |> redirect(to: hero_path(conn, :show, hero))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html",
          changeset: changeset,
          heroes_types: get_heroes_types_opts,
          heroes_roles: get_heroes_roles_opts)
    end
  end

  def show(conn, %{"id" => id}) do
    hero = Heroes.get_hero!(id)
    render(conn, "show.html", hero: hero)
  end

  def edit(conn, %{"id" => id}) do
    hero = Heroes.get_hero!(id)
    changeset = Heroes.change_hero(hero)
    render(conn, "edit.html", hero: hero, changeset: changeset,
    heroes_types: get_heroes_types_opts,
    heroes_roles: get_heroes_roles_opts)
  end

  def update(conn, %{"id" => id, "hero" => hero_params}) do
    hero = Heroes.get_hero!(id)

    case Heroes.update_hero(hero, hero_params) do
      {:ok, hero} ->
        conn
        |> put_flash(:info, "Hero updated successfully.")
        |> redirect(to: hero_path(conn, :show, hero))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", hero: hero, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    hero = Heroes.get_hero!(id)
    {:ok, _hero} = Heroes.delete_hero(hero)

    conn
    |> put_flash(:info, "Hero deleted successfully.")
    |> redirect(to: hero_path(conn, :index))
  end
end

lib/heroes_oracle_web/views/hero_view.ex
defmodule HeroesOracleWeb.HeroView do
  use HeroesOracleWeb, :view
end

lib/heroes_oracle_web/templates/hero/edit.html.eex
<h2>Edit Hero</h2>

<%= render "form.html", Map.put(assigns, :action, hero_path(@conn, :update, @hero)) %>

<span><%= link "Back", to: hero_path(@conn, :show, @hero.id) %></span>

lib/heroes_oracle_web/templates/hero/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :select_a_role, class: "control-label" %>
    <%= select f, :role_id, [{"", nil}] ++ @heroes_roles, class: "form-control" %>
    <%= error_tag f, :role_id %>
  </div>

  <div class="form-group">
    <%= label f, :select_a_type, class: "control-label" %>
    <%= select f, :type_id, [{"", nil}] ++ @heroes_types, class: "form-control" %>
    <%= error_tag f, :type_id %>
  </div>


  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/heroes_oracle_web/templates/hero/index.html.eex
<h2>Listing Heroes</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Type</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for hero <- @heroes do %>
    <tr>
      <td><%= hero.name %></td>
      <td><%= hero.role.name %></td>
      <td><%= hero.type.name %></td>

      <td class="text-right">
        <span><%= link "Show", to: hero_path(@conn, :show, hero), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: hero_path(@conn, :edit, hero), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: hero_path(@conn, :delete, hero), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Hero", to: hero_path(@conn, :new) %></span>

lib/heroes_oracle_web/templates/hero/new.html.eex
<h2>New Hero</h2>

<%= render "form.html", Map.put(assigns, :action, hero_path(@conn, :create)) %>

<span><%= link "Back", to: hero_path(@conn, :index) %></span>

lib/heroes_oracle_web/templates/hero/show.html.eex
<h2>Show Hero</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @hero.name %>
  </li>

</ul>

<span><%= link "Edit", to: hero_path(@conn, :edit, @hero) %></span>
<span><%= link "Back", to: hero_path(@conn, :index) %></span>


<div>
  <h3>
    Talents
    <span><%= link "[edit]", to: hero_talent_path(@conn, :index, @hero.id) %></span>
  </h3>
  <table class="table">
    <thead>
      <tr>
        <th>Level</th>
        <th>Name</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <%= for talent <- @hero.talents do %>
        <tr>
          <td><%= talent.level %></td>
          <td><%= talent.name %></td>
          <td><%= talent.description %></td>
        </tr>
      <%= end %>
    </tbody>
  <table>
</div>